server:
  port: 8080

spring:
  application:
    name: spring-elasticsearch-example

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 10s
    socket-timeout: 60s

logging:
  level:
    com.example.elk: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,elasticsearch
  endpoint:
    health:
      show-details: always